version: '3'
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.backend
    env_file: ./backend/dev.env
    ports:
     - "${BACKEND_PORT}:8080"
    depends_on:
      - db
  frontend:
    container_name: frontend
    env_file: "./frontend/dev.env"
    build:
      context: "."
      dockerfile: ./Dockerfile.frontend
      args: 
        - BACKEND_URL=$REACT_APP_BACKENDAPI_URL
        - BACKEND_PORT=$REACT_APP_BACKENDAPI_PORT
    
    ports:
      - "${FRONTEND_PORT}:80"
    
  
  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgres/data
    env_file: ./backend/dev.env
    ports:
      - "5432:5432"