version: '3'
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile.backend
    env_file: ./backend/dev.env
    ports:
     - "${BACKEND_PORT}:8080"
    depends_on:
      - db
  