FROM python:3.9.1-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY backend backend
COPY backend/requirements.txt /app/backend/requirements.txt 
RUN python -m pip install --upgrade pip
RUN apt update \
    && pip install -r /app/backend/requirements.txt \
    && rm -rf /root/.cache/pip

WORKDIR /app/backend
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]