FROM node:18-alpine AS develop-stage
WORKDIR /app
COPY frontend/public ./public
COPY frontend/src ./src
COPY frontend/package*.json ./
RUN npm install
COPY . .
ARG BACKEND_PORT
ARG BACKEND_URL
ENV REACT_APP_BACKENDAPI_PORT $BACKEND_PORT
ENV REACT_APP_BACKENDAPI_URL $BACKEND_URL

RUN echo $REACT_APP_BACKENDAPI_PORT
RUN echo $REACT_APP_BACKENDAPI_URL
# Build stage: Use the development stage as a base, run npm build to generate production-ready assets
FROM develop-stage AS build-stage
RUN npm run build

# Production stage: Use Nginx 1.15.7 Alpine as the base image, copy the built assets from the build stage, expose port 80, and start Nginx
FROM nginx:1.15.7-alpine AS production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]